' <auto-generated />
Imports System.CodeDom.Compiler
Imports System.Data.Entity.Migrations
Imports System.Data.Entity.Migrations.Infrastructure
Imports System.Resources

Namespace Migrations
    <GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")>
    Public NotInheritable Partial Class alter_tables_CategRemu_DetCommis_HistoMvt_JournCaiss_Retrait_Set_Decimal_as_money_Field
        Implements IMigrationMetadata
    
        Private ReadOnly Resources As New ResourceManager(GetType(alter_tables_CategRemu_DetCommis_HistoMvt_JournCaiss_Retrait_Set_Decimal_as_money_Field))
        
        Private ReadOnly Property IMigrationMetadata_Id() As String Implements IMigrationMetadata.Id
            Get
                Return "202107211546254_alter_tables_CategRemu_DetCommis_HistoMvt_JournCaiss_Retrait_Set_Decimal_as_money_Field"
            End Get
        End Property
        
        Private ReadOnly Property IMigrationMetadata_Source() As String Implements IMigrationMetadata.Source
            Get
                Return Nothing
            End Get
        End Property
        
        Private ReadOnly Property IMigrationMetadata_Target() As String Implements IMigrationMetadata.Target
            Get
                Return Resources.GetString("Target")
            End Get
        End Property
    End Class
End Namespace
